// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLYP8X86c3_tcel38RzRgzV7-DGa1OuZs',
    appId: '1:371543486564:web:f15ab550708ff0e2842f71',
    messagingSenderId: '371543486564',
    projectId: 'finalyearproj-ae96b',
    authDomain: 'finalyearproj-ae96b.firebaseapp.com',
    storageBucket: 'finalyearproj-ae96b.firebasestorage.app',
    measurementId: 'G-TH581Z3Z90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFDt1T2IgL9ATNxDqBzl3B3-BivLNXzH0',
    appId: '1:371543486564:android:51b37da01ff27b88842f71',
    messagingSenderId: '371543486564',
    projectId: 'finalyearproj-ae96b',
    storageBucket: 'finalyearproj-ae96b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVcSKeVz6a4AwXJbirM7kZgnl0LxRQrqU',
    appId: '1:371543486564:ios:6088afaacfb7685b842f71',
    messagingSenderId: '371543486564',
    projectId: 'finalyearproj-ae96b',
    storageBucket: 'finalyearproj-ae96b.firebasestorage.app',
    iosBundleId: 'com.fjwu.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVcSKeVz6a4AwXJbirM7kZgnl0LxRQrqU',
    appId: '1:371543486564:ios:6088afaacfb7685b842f71',
    messagingSenderId: '371543486564',
    projectId: 'finalyearproj-ae96b',
    storageBucket: 'finalyearproj-ae96b.firebasestorage.app',
    iosBundleId: 'com.fjwu.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLYP8X86c3_tcel38RzRgzV7-DGa1OuZs',
    appId: '1:371543486564:web:1e00b0f2a1f73873842f71',
    messagingSenderId: '371543486564',
    projectId: 'finalyearproj-ae96b',
    authDomain: 'finalyearproj-ae96b.firebaseapp.com',
    storageBucket: 'finalyearproj-ae96b.firebasestorage.app',
    measurementId: 'G-7ZH3F5WY67',
  );

}